openapi: 3.0.1
info:
  title: STD21027
  description: Hello word!.
  
  version: 1.0.0

servers:
- url: https://std21027.com
tags:
- name: Students
- name: Course

paths:

  /students:
    post:
      tags:
      - Students
      summary: Create new student
      operationId: addPet
      requestBody:
        description: Students to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudent'
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateStudent'
        required: true
      responses:
        200:
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
        400:
          description: Bad request

    get:
      tags:
      - Students
      summary: Get all students
      description: Get all students with details
      operationId: findPetsByStatus
      parameters:
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: page_size
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        200:
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
        400:
          description: Bad request
        
components:
  schemas:
    Student:
      required:
      - name
      - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: String
    CreateStudent:
      required:
      - name
      - photoUrls
      type: object
      properties:
        name:
          type: string
          example: String
